# GameNGen Configuration - Tier 1 (Chrome Dino)

# Project Settings
project_name: "gamengen-chrome-dino"
experiment_name: "tier1-proof-of-concept"
seed: 42

# Hardware
device: "cuda"  # or "cpu"
num_workers: 4
mixed_precision: true  # fp16 training

# Paths
data_dir: "data/recordings"
checkpoint_dir: "checkpoints"
log_dir: "logs"

# Environment Settings (Chrome Dino)
environment:
  name: "chrome_dino"
  num_actions: 3  # 0=no action, 1=jump, 2=duck
  resolution:
    width: 512
    height: 256
  frame_stack: 4
  action_repeat: 1
  grayscale: false

# RL Agent Settings (DQN)
agent:
  algorithm: "DQN"
  total_episodes: 2000
  buffer_size: 10000
  learning_rate: 1e-4
  batch_size: 64
  gamma: 0.99  # discount factor
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 0.9995
  target_update: 1000
  learning_starts: 1000
  train_freq: 4
  save_freq: 100  # episodes

# Data Collection
data_collection:
  episodes_to_collect: 2000
  frames_per_episode: 500  # approximate
  save_frequency: 10  # save every N episodes
  compress: true

# Diffusion Model Settings
diffusion:
  # Base Model
  pretrained_model: "CompVis/stable-diffusion-v1-4"
  resolution:
    width: 512
    height: 256
  latent_channels: 4

  # Context
  context_length: 32  # number of past frames
  action_embedding_dim: 128

  # Training
  batch_size: 32  # Adjusted for 16GB VRAM
  num_train_steps: 3000
  learning_rate: 2e-5
  gradient_accumulation_steps: 1
  gradient_clip: 1.0

  # Optimizer
  optimizer: "AdamW"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8

  # Noise Augmentation (Critical!)
  noise_augmentation:
    enabled: true
    max_noise_level: 0.7
    num_buckets: 10

  # Scheduler
  lr_scheduler: "constant"
  warmup_steps: 0

  # CFG (Classifier-Free Guidance)
  cfg_drop_prob: 0.1  # probability to drop context frames
  cfg_scale: 1.5

  # Checkpointing
  save_every_n_steps: 500
  eval_every_n_steps: 500
  keep_last_n_checkpoints: 3

# Decoder Fine-tuning
decoder:
  enabled: false  # Can enable after initial training
  learning_rate: 1e-4
  batch_size: 64
  num_steps: 1000

# Inference Settings
inference:
  num_sampling_steps: 4  # DDIM steps
  cfg_scale: 1.5
  add_noise_level: 0.0  # noise added to context frames at inference
  fps: 20  # target framerate

# Evaluation
evaluation:
  compute_metrics: true
  metrics:
    - "psnr"
    - "lpips"
    - "ssim"
  num_eval_trajectories: 64
  eval_trajectory_length: 100  # frames

# Logging
logging:
  use_wandb: false  # Set to true if using Weights & Biases
  wandb_project: "gamengen"
  log_interval: 10  # steps
  save_samples: true
  num_samples_to_save: 4

# Debugging
debug:
  enabled: false
  overfit_single_batch: false
  limit_train_batches: null  # set to number to limit
  profile: false
