name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install diffusers stable-baselines3 gymnasium lpips scikit-image
        pip install pyyaml omegaconf tqdm

    - name: Run import tests
      run: |
        python -c "from src.diffusion.model import ActionConditionedDiffusionModel; print('✓ Imports work')"
        python -c "from src.agent.dqn_agent import DQNAgent; print('✓ DQN imports work')"

    - name: Run quick tests
      run: |
        python tests/quick_test_simple.py

    - name: Verify project structure
      run: |
        test -f README.md || exit 1
        test -f LICENSE || exit 1
        test -d src/diffusion || exit 1
        test -d src/agent || exit 1
        test -d configs || exit 1
        test -d tests || exit 1
        echo "✓ Project structure OK"

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools
      run: |
        pip install flake8 black isort

    - name: Check code formatting with black
      run: |
        black --check --diff src/

    - name: Check imports with isort
      run: |
        isort --check-only src/

    - name: Lint with flake8
      run: |
        flake8 src/ --max-line-length=100 --ignore=E203,W503
